sw_application_homepage:
    pattern:  /
    defaults: { _controller: SwApplicationBundle:Default:index }

sw_application_swimmingpools_list:
    pattern:  /swimming-pools/
    defaults: { _controller: SwApplicationBundle:Default:getSwimmingPools }
    requirements:
        _method:  GET
        _format:  json
