sw_application_homepage:
    pattern:  /
    defaults: { _controller: SwApplicationBundle:Default:index }

sw_application_swimmingpools_list:
    pattern:  /swimming-pools/
    defaults: { _controller: SwApplicationBundle:Default:getSwimmingPools }
    requirements:
        _method:  GET
        _format:  json

sw_application_comments:
    pattern:  /swimming-pools/{id}/comments
    defaults: { _controller: SwApplicationBundle:Default:getComments, id: 0}
    requirements:
        _method:  GET
        _format:  json
