sw_application_homepage:
    pattern:  /
    defaults: { _controller: SwApplicationBundle:Default:index }

sw_application_list:
    pattern:  /piscines
    defaults: { _controller: SwApplicationBundle:Default:list }

# Comment
sw_application_swimmingpools_comments_create:
    pattern:  /comment/create
    defaults: { _controller: SwApplicationBundle:Default:createComment }
    requirements:
        _method:  POST

# Json API
sw_application_swimmingpools_list:
    pattern:  /swimming-pools
    defaults: { _controller: SwApplicationBundle:Default:getSwimmingPools }
    requirements:
        _method:  GET
        _format:  json

sw_application_swimmingpools_show:
    pattern:  /swimming-pools/{id}
    defaults: { _controller: SwApplicationBundle:Default:getSwimmingPool }
    requirements:
        _method:  GET
        _format:  json

#sw_application_comments:
    #pattern:  /swimming-pools/{id}/comments
    #defaults: { _controller: SwApplicationBundle:Default:getComments, id: 0}
    #requirements:
        #_method:  GET
        #_format:  json

# SOAP API
sw_application_swimmingpools_add_comment:
    pattern:  /swimming-pool/comment/add
    defaults: { _controller: SwApplicationBundle:SoapClient:addComment }
    #condition: "request.headers.get('X-Requested-With') == 'XmlHttpRequest'"

sw_application_swimmingpools_get_comment:
    pattern:  /swimming-pool/{swimmingPoolId}/comment
    defaults: { _controller: SwApplicationBundle:SoapClient:getComments, swimmingPoolId : 1 }
    #condition: "request.headers.get('X-Requested-With') == 'XmlHttpRequest'"
