sw_rest_swimming:
    type: rest
    prefix: /
    resource: "@SwRestSwimmingBundle/Resources/config/routing.yml"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
