sw_application:
    resource: "@SwApplicationBundle/Resources/config/routing.yml"
    prefix:   /

sw_soap_comment:
    resource: "@SwSoapCommentBundle/Resources/config/routing.yml"
    prefix:   /soap/

sw_rest_swimming:
    type: rest
    prefix: /
    resource: "@SwRestSwimmingBundle/Resources/config/routing.yml"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

_besimple_soap:
    resource: "@BeSimpleSoapBundle/Resources/config/routing/webservicecontroller.xml"
    prefix:   /ws
